version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - ./code:/var/www/html
    ports:
      - "8082:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    container_name: php-82
    networks:
      - laravel
networks:
    laravel:
        driver: bridge
